### ISSUE TITLE
--name completions failing 

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurecli#10]
Insiders 1.13.0-insiders
Windows 10

```bash
D:\src\myExpApp>az --version
azure-cli (2.0.6)
```

``` bash
az login
az group create --name myResourceGroup --location westus
az configure --defaults group=myResourceGroup location=westus
az appservice plan create --name myPlan --sku F1
az webapp create --name myexpressapp-cdias --plan myplan
az webapp browse --name <press ctrl+space>
```

Result: never get completions for `--name` parameter with a list of sites to browse
I verified that `az interactive` gives me this information.

![image](https://cloud.githubusercontent.com/assets/1487073/26815168/98df2496-4a3f-11e7-94d1-f8187607f694.png)

**Comment by chrmarti** [comment]
Works for me on Windows 10 with the latest. Please reopen if this is still an issue.
