### ISSUE TITLE
completion performance on windows

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurecli#11]
Completions on Windows are very slow... at least 5-6 seconds before the list appears.  `az interactive` is almost instant.

![azcli](https://cloud.githubusercontent.com/assets/1487073/26815533/c4da7314-4a41-11e7-9a75-94f8fb5679b5.gif)

**Comment by chrmarti** [comment]
This seemed to be fixed with the update to Azure CLI 2.0.24. Please reopen if this is still an issue.
