### ISSUE TITLE
No intellisense/autocomplete

### ISSUE THREAD

**Issue by lunar87** [Microsoft/vscode-azurecli#19]
Running VSCode on Windows, installed CLI, running commands works, but there is no intellisense

**Comment by chrisdias** [comment]
I'm seeing the same things. The performance of Python and the underlying CLI on Windows seems to be an issue. You have to wait for the extension to pick up the login (you'll see the status in the status bar) and then you will start to see completions.  However, if you type quickly, back up, etc. you can see the completion list gets confused. Here I'm at `az` but it is showing me completions for `webapp`:

![image](https://user-images.githubusercontent.com/1487073/30006072-1bfd6792-90a5-11e7-9a7b-e6422e6df98c.png)

I think this is because I typed in `az webapp` a few times, backed up, press `ctrl+space` a few times, etc.

**Comment by chrisdias** [comment]
az cli version 2.0.15
python version 3.6.1

**Comment by chrisdias** [comment]
related to #13 and #15 ?

**Comment by chrisdias** [comment]
works *much* better on windows!

**Comment by vykhand** [comment]
Dear all,  I am on az 2.0.18, and the issue still takes place. Can we please reopen the issue?
Some times I notice that if I start typing it gives me suggestions (not always!) but what I press ctrl-space it shows loading.

![image](https://user-images.githubusercontent.com/498481/31630019-97044a46-b2b5-11e7-8c91-0ab4633f29df.png)

**Comment by chrisdias** [comment]
@chrmarti i'm seeing the same regression of the experience on windows over the weekend...

**Comment by chrmarti** [comment]
Cannot reproduce with az 2.0.20, could you retry with that?

**Comment by chrmarti** [comment]
@jonathanmoons @chrisdias Could you retry with the latest CLI? (It worked for me with 2.0.20.)

**Comment by blelem** [comment]
Same problem here. Text is colored ok, running commands works, but intellisense doesn't offer any suggestions.
azure-cli (2.0.27)
VScode version 1.20
python version 3.6.4
Mac High Sierra
![screen shot 2018-02-23 at 15 10 01](https://user-images.githubusercontent.com/2476938/36595664-b96d2dd0-18ab-11e8-84c5-ee760408bbbc.png)

**Comment by vykhand** [comment]
Hi guys, I still have this problem. What do you think is the root cause? If you point me to it I may try to fix it.

**Comment by chrmarti** [comment]
@vykhand Which versions of this extension, VS Code and the Azure CLI are you using? Make sure all are at the latest released version. If the problem persists, please check if there are any errors in the console (Help > Toggle Developer Tools).

**Comment by mcollier** [comment]
Same problems for me.

- Version 1.21.1
- Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
- Date 2018-03-14T14:46:47.128Z
- Shell 1.7.9
- Renderer 58.0.3029.110
- Node 7.9.0
- Architecture x64

Azure CLI Tools v0.4.1

Azure CLI 2.0.30

Python 3.6.0 :: Anaconda 4.3.0

<img width="1639" alt="vscode azure cli tool error" src="https://user-images.githubusercontent.com/1142273/38334367-1f5180a0-3829-11e8-8521-c007cd3cafcf.png">

**Comment by chrmarti** [comment]
The stacktrace suggests that you are running a CLI version < 2.0.24. Could there be an old version on the PATH? What is the CLI version you get when running `az --version` from a command prompt?

**Comment by vykhand** [comment]
Hi Christof, @chrmarti I am running az cli that is installed together with [Azure Machine Learning workbench](https://docs.microsoft.com/en-us/azure/machine-learning/preview/quickstart-installation). In the past, I tried to update to the latest version and it did not help the issue. 



C:\10.DEV_REPOS\kaggle-jigsaw>az --version
azure-cli (2.0.17)

VS Code:
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by mcollier** [comment]
@chrmarti Running `az --version` results in **2.0.30**.

Where do you see the suggestion that the Azure CLI is < 2.0.24?

**Comment by chrmarti** [comment]
@vykhand Please update to the latest CLI version. We had reports of significant performance improvements starting with 2.0.24.

@mcollier I see it using the pre-2.0.24 CLI's API in your screenshot. That also shows it using CLI modules in your `AppData\Roaming` folder when it should use those in `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2`. For some reason it mixes up the two versions. What is your `PYTHONPATH` set to?

**Comment by chrmarti** [comment]
@mcollier What do you get for `"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import sys; print('\n'.join(sys.path))"`?

**Comment by chrmarti** [comment]
@derekbekoe Any idea why the `AppData\Roaming` folder makes it to the lookup paths?

**Comment by mcollier** [comment]
@chrmarti Is there a way to reopen this issue?  

@derekbekoe Any thoughts on the AppData\Roaming question asked by @chrmarti?

**Comment by alandevos** [comment]
having the same issue. console displays following error:

`C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe: No module named azservice`

**Comment by chrmarti** [comment]
@alandevos What do you get for `"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import sys; print('\n'.join(sys.path))"`?

**Comment by alandevos** [comment]
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python36.zip
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages

**Comment by chrmarti** [comment]
@alandevos We will track your issue as #35.

**Comment by chrmarti** [comment]
Could everyone seeing this update to the latest Azure CLI (2.0.37) and Azure CLI extension (0.4.2) and check if this is still a problem?

**Comment by chrmarti** [comment]
@samhodgkinson Are there any errors in the console (Help > Toggle Developer Tools)?

**Comment by samhodgkinson** [comment]
There are a few issues but none I can see for ms-vscode.azurecli, let me know If there are any log files I can attach.

**Comment by mantakaras** [comment]
Azure cli -2.062
Python  3.6.6
win 10

**Comment by vermegi** [comment]
Same issue here 
azure cli 2.0.62
windows 10 
azcli tools 0.4.4
![image](https://user-images.githubusercontent.com/1042817/56340408-55493200-61a1-11e9-9cea-0ccf9190ee22.png)

**Comment by Shaun-Cox** [comment]
Same issue here.  

```
console.ts:134 [Extension Host] Traceback (most recent call last):
  File "C:\Users\shaun\.vscode\extensions\ms-vscode.azurecli-0.4.4\service\start.py", line 6, in <module>
    import azservice.__main__
  File "C:\Users\shaun\.vscode\extensions\ms-vscode.azurecli-0.4.4\service\azservice\__main__.py", line 17, in <module>
    from azservice.tooling import GLOBAL_ARGUMENTS, initialize, load_command_table, get_help, get_current_subscription, get_configured_defaults, get_defaults, is_required, run_argument_value_completer, get_arguments, load_arguments, arguments_loaded
  File "C:\Users\shaun\.vscode\extensions\ms-vscode.azurecli-0.4.4\service\azservice\tooling.py", line 12, in <module>
    from azservice.tooling2 import GLOBAL_ARGUMENTS, initialize, load_command_table, get_help, get_current_subscription, get_configured_defaults, get_defaults, is_required, run_argument_value_completer, get_arguments, load_arguments, arguments_loaded
  File "C:\Users\shaun\.vscode\extensions\ms-vscode.azurecli-0.4.4\service\azservice\tooling2.py", line 17, in <module>
    from azure.cli.core._config import GLOBAL_CONFIG_PATH, DEFAULTS_SECTION
ImportError: cannot import name 'DEFAULTS_SECTION'
```

```
VSCode Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```

```
Id: ms-vscode.azurecli
Version: 0.4.4
```

```
azure-cli 2.0.62
Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\shaun\.azure\cliextensions'
Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.
```

```
> "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe" -c "import sys; print('\n'.join(sys.path))"
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python36.zip
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\DLLs
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\win32
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\win32\lib
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\Pythonwin

```

**Comment by LudwikBielczynski** [comment]
Same issue here:
`
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/az/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ludwik/.vscode/extensions/ms-vscode.azurecli-0.4.4/service/azservice/__main__.py", line 17, in <module>
    from azservice.tooling import GLOBAL_ARGUMENTS, initialize, load_command_table, get_help, get_current_subscription, get_configured_defaults, get_defaults, is_required, run_argument_value_completer, get_arguments, load_arguments, arguments_loaded
  File "/home/ludwik/.vscode/extensions/ms-vscode.azurecli-0.4.4/service/azservice/tooling.py", line 12, in <module>
    from azservice.tooling2 import GLOBAL_ARGUMENTS, initialize, load_command_table, get_help, get_current_subscription, get_configured_defaults, get_defaults, is_required, run_argument_value_completer, get_arguments, load_arguments, arguments_loaded
  File "/home/ludwik/.vscode/extensions/ms-vscode.azurecli-0.4.4/service/azservice/tooling2.py", line 17, in <module>
    from azure.cli.core._config import GLOBAL_CONFIG_PATH, DEFAULTS_SECTION
ImportError: cannot import name 'DEFAULTS_SECTION'
`

**Comment by chrmarti** [comment]
Let's track the latest reports in #50 which specifically for the reported issue with 2.0.62 of the CLI.

I'll close this very old issue. If you see other problems with IntelliSense than the one in #50, please open a new issue.

**Comment by devdeer-yashas** [comment]
azure-cli version : "2.42.0". Intellisense fails after a few minutes in VS code. on pressing ctrl + space it just says loading.
