### ISSUE TITLE
No completions on az webapp create --plan

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-azurecli#20]
macos, insiders latest

create a new app service plan (actually run the commands):

``` console
az login
az account list -o table
az group create --name testazcli-rg --location westus
az appservice plan create --name testazcli-name --resource-group testazcli-rg --location westus --sku FREE 
```

Now try to get IntelliSense on the --plan:

``` console
az webapp create --name cdias-testazcli-site --plan 
```

result: no completions:

![image](https://user-images.githubusercontent.com/1487073/30400283-3aa10148-988b-11e7-803e-bff55478db39.png)

**Comment by chrmarti** [comment]
Works for me. Is there anything in the console?

**Comment by chrmarti** [comment]
This cleared after upgrading `az`, if I remember correctly. I have also improved error handling for when the Python scripts crashes.
