### ISSUE TITLE
Completions not available showing loading

### ISSUE THREAD

**Issue by vykhand** [Microsoft/vscode-azurecli#22]
Often when I open VS Code and start writing commands in azcli file, the suggestions are not available. I start entering command, it does not suggest anything. If I hit Ctrl-Space, it is showing "loading" for a long time. I am logged in with az and if I type az account list in terminal - it works

![image](https://user-images.githubusercontent.com/498481/30692879-90693f94-9ecd-11e7-9be5-5b0b20ff17de.png)

**Comment by chrmarti** [comment]
@vykhand Is this on Windows? (We have a fix there we want to publish soon.)

**Comment by vykhand** [comment]
@chrmarti yeap, it is on Win10 x64.

**Comment by chrmarti** [comment]
Thanks. Duplicate of #19. Also make sure you're on the latest version of `az`.
