### ISSUE TITLE
EOL Issues

### ISSUE THREAD

**Issue by deltadan** [Microsoft/vscode-azurecli#24]
Ok, after a TON of pain I've determined that if you write a new bash script using this exention and then just try to save as a .sh file then the EOL characters are incorrect.  I spent hours trying to figure out what the problem was until I just pulled the files into Notepad++ and did their simple EOL conversion.

I would suggest that this is a bug as there is no reason why unix EOL shouldn't be used when creating a .azcli file.
Thanks,
Dan Patrick
Azure MVP
dan@opsgility.com

**Comment by deltadan** [comment]
I've come to realize that this is true if I create a .sh file from scratch as well, so I would suggest looking into how to fix this with another plug-in or something.

Thanks,
Dan

**Comment by chrmarti** [comment]
Have you tried the [.editorconfig](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) extension with:
```
[*.sh]
end_of_line = lf
```
That seems to work for me.
