### ISSUE TITLE
when trying to push to azure registry, I have to manually run az acr login from the command line

### ISSUE THREAD

**Issue by MaurGi** [Microsoft/vscode-azurecli#26]
CLI tools - Release 0.3.0

My VS Code version:
![image](https://user-images.githubusercontent.com/13138584/32973928-6932a672-cbaf-11e7-811d-1ac7f09f9f57.png)

**Comment by chrmarti** [comment]
What would the expected behavior be? (I think the registry has a separate username and password.)

**Comment by MaurGi** [comment]
Sorry this bug is poorly written, I was in a rush - my expectation is to prompt for username and password, like it does for DockerHub - if you select DockerHub under registries, you are prompted for a username: 
![image](https://user-images.githubusercontent.com/13138584/33029204-d8e8e9c6-cdcc-11e7-80a3-a07724d2ac6e.png)
The same is not true if you select Azure as registry -

thx

**Comment by chrmarti** [comment]
Got it, are you using the Docker extension? This might be a request going to that extension.

**Comment by MaurGi** [comment]
I am - 
I have Docker extension version 0.0.22 - thx.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-docker#177
