### ISSUE TITLE
Is there a preferred terminal to run CLI commands in?

### ISSUE THREAD

**Issue by bdelaney** [Microsoft/vscode-azurecli#28]
I notice bash in the example you show. I sometimes see cmd, sometimes powershell, sometimes python when I use the extension to 'run line in terminal.'
Does it matter?

**Comment by chrisdias** [comment]
@bdelaney you can [configure VS Code to run different shells in the terminal](https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration) (e.g. cmd or powershell on windows, bash or zsh on Mac, etc.).  `Run line in terminal` simply takes the line and pipes it to the terminal, as if you typed it in yourself.  As long as you have the [Azure CLI installed](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest) and have access to it on the path from the terminal then you should be fine.
