### ISSUE TITLE
Execute entire .azcli file at once

### ISSUE THREAD

**Issue by ThorstenHans** [Microsoft/vscode-azurecli#32]
Hey,

I'd love to see a command to execute the entire `.azcli` script at once. Are there plans to implement such a feature?

**Comment by chrmarti** [comment]
You can do that with a task. E.g., on Linux/Mac (couldn't find the syntax for Windows' PowerShell rightaway) use the following `.vscode/tasks.json`:
```jsonc
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Execute Current File",
			"type": "shell",
			"command": "source ${file}",
			"problemMatcher": []
		}
	]
}
```

**Comment by ThorstenHans** [comment]
Cool, thanks!
