### ISSUE TITLE
Provide full hotkeys documentation

### ISSUE THREAD

**Issue by marb21** [Microsoft/vscode-azurecli#33]
First of all.. This is an awesome extension!
I would like to understand all the hotkeys. For example, after writing "az vm create"... press any hotkey and automatically write the required parameters to create a VM.

Thanks!

**Comment by chrmarti** [comment]
There are not that many. There is a list on the "Contributions" tab when you open the extension from the extensions viewlet:
![image](https://user-images.githubusercontent.com/9205389/37950521-1b83b966-3199-11e8-87e9-3ecc40b2ef06.png)

"Toggle Live Query" is somewhat experimental and updates what you see in the editor opened to the right after running "Run Line in Editor".

To get the list of required options you can use one of the snippets: On a new line of a .azcli file type `createvm` and press Enter to insert that snippet.
