### ISSUE TITLE
What it `tick` symbol allowing to send input to terminal?

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/vscode-azurecli#34]
Hello,

On video below presenter said that pressing `Ctrl-Tick` symbol will send  input from AZCLI file to terminal window. What is exactly that combination?

https://youtu.be/I_UIsbLKBpg

**Comment by chrmarti** [comment]
On Windows and Linux it's `Ctrl + '` (single tick or apostrophe), on Mac it's `Cmd + '`.

If that doesn't work, it might have been remapped. You can check what the current shortcut is in `File > Preferences > Keyboard Shortcuts` where you can search for `azure` or `azurecli`.
