### ISSUE TITLE
No IntelliSense with latest Azure CLI

### ISSUE THREAD

**Issue by Nan0106** [Microsoft/vscode-azurecli#35]
Issue Type: <b>Bug</b>

Azure CLI Tools no intellisense.
Visual Studio Code Console shows:
"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe: No module named azservice"

Extension version: 0.4.1
VS Code version: Code 1.24.0 (6a6e02cef0f2122ee1469765b704faf5d0e0d859, 2018-06-06T17:35:40.560Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (2.29GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|50%|

</details>

**Comment by chrmarti** [comment]
This appears to be a problem with the latest Azure CLI on Windows. I'm investigating.

**Comment by chrmarti** [comment]
Published 0.4.2 of the extension with the fix for this.

**Comment by Nan0106** [comment]
@chrmarti Thank you.
