### ISSUE TITLE
Intellisense doesn't work

### ISSUE THREAD

**Issue by stenastena** [Microsoft/vscode-azurecli#38]
Issue Type: <b>Bug</b>

I installed an extension Azure CLI Tools and feature Intellisense doesn't autocomplete.
I reinstalled the extension. It didn't help. I deleted VS Code and deleted .vscode direcory in my profile. After that I upgraded Azure CLI,  installed last version of VS Code, installed extension Azure Cli Tools, added to the Path environment variable the exect path to Python, rebooted Windows. It didn't help.
I saw in the frame "Developer Tools" and see that there are some errors, see they later.

My version of software are:
azure-cli (2.0.41)
Azure CLI Tools 0.4.2
VS Code:
Version: 1.25.0
Commit: 0f080e5267e829de46638128001aeb7ca2d6d50e
Date: 2018-07-05T13:11:58.697Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

Python (Windows) 3.6.5

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] Exit code 1, signal null
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] Python process terminated with exit code 1, signal null.
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] �� �ணࠬ�� �������஢��� ��㯯���� ����⨪��. �� �������⥫�묨 ᢥ����ﬨ ���頩��� � ��⥬���� ������������.

t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] Exit code 1, signal null
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1376   ERR An unknown error occurred. Please consult the log for more details.
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] �� �ணࠬ�� �������஢��� ��㯯���� ����⨪��. �� �������⥫�묨 ᢥ����ﬨ ���頩��� � ��⥬���� ������������.

t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270 [Extension Host] Exit code 1, signal null
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:270
console.ts:136 [Extension Host] �� �ணࠬ�� �������஢��� ��㯯���� ����⨪��. �� �������⥫�묨 ᢥ����ﬨ ���頩��� � ��⥬���� ������������.

t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:136 [Extension Host] Exit code 1, signal null
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
log.ts:171   ERR An unknown error occurred. Please consult the log for more details.
console.ts:136 [Extension Host] �� �ணࠬ�� �������஢��� ��㯯���� ����⨪��. �� �������⥫�묨 ᢥ����ﬨ ���頩��� � ��⥬���� ������������.

t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:136 [Extension Host] Exit code 1, signal null
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
log.ts:171   ERR An unknown error occurred. Please consult the log for more details.

Extension version: 0.4.2
VS Code version: Code 1.25.0 (0f080e5267e829de46638128001aeb7ca2d6d50e, 2018-07-05T13:11:58.697Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (2.79GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by stenastena** [comment]
It worked! Must be run as administrator.

**Comment by chrmarti** [comment]
Do you have an idea why it needs to be run as administrator?
