### ISSUE TITLE
Even useful without azurecli

### ISSUE THREAD

**Issue by tmds** [microsoft/vscode-azurecli#4]
I like being able to put some commands in a file and then be able to select and execute some of them on the fly.

It would be nice if there was completion for other commands, similar to how it is available in a terminal.

**Comment by Jarlotee** [comment]
I would like to second this.

The syntax highlighting for az is awesome but I can't run this from the command line or copy and paste it to a script file without further formatting

Have you considered supporting `.azcli.sh` or .azcli.ps1`  and adding the appropriate syntax highlighting?

It would make this plugin infinitely more useful!

**Comment by FoldZero** [comment]
yes, .azcli does not support auto formatting (like .ps1 does) in vscode. This could also be expanded upon.

**Comment by tmds** [comment]
Closing due to age.
