### ISSUE TITLE
az sql database VSS auto complete lists arguments like --database-name & --server-name

### ISSUE THREAD

**Issue by sameershaikgithub** [Microsoft/vscode-azurecli#42]
in VSS:
az sql db create  (auto complete shows --database-name & --server-name, instead of  --name & --server)

correct syntax:
az sql db create --name shaiksdb --resource-group cligroup --server shaikssqlserver

az: error: unrecognized arguments: --database-name shaiksdb --server-name shaikssqlserver

screenshot attached
<img width="558" alt="screen shot 2019-01-05 at 6 51 05 pm" src="https://user-images.githubusercontent.com/20804460/50730460-3e179480-111c-11e9-9237-cc2bfb11e8ca.png">

**Comment by chrmarti** [comment]
We are reading these from the CLI itself. `az interactive` shows the same (wrong) argument names for `sql db create --help`.

**Comment by chrmarti** [comment]
This issue was moved to Azure/azure-cli#8179
