### ISSUE TITLE
Using variables instead of string

### ISSUE THREAD

**Issue by TechWatching** [Microsoft/vscode-azurecli#43]
Is it possible to use variables in an azure cli scrapbook when using it on Windows ?
I want to be able things like that :

`az group show --resource-group $resourceGroup`

**Comment by chrmarti** [comment]
Since you execute the script line-by-line in the terminal, you can add `export resourceGroup=your-group` to the script or type that in the terminal before you run parts of your script. There is currently no other way to bring in variables than what your terminal shell supports.

Does that help?

**Comment by TechWatching** [comment]
Ok thanks for your answer.

**Comment by Mahesh-MSFT** [comment]
i think adding support for variables will help drive adoption. It is not practical to set so many variables ([example](https://docs.microsoft.com/en-us/azure/aks/limit-egress-traffic) below) each time on the terminal before switching back to scrapbook.

```Bash
PREFIX="aks-egress"
RG="${PREFIX}-rg"
LOC="eastus"
PLUGIN=azure
AKSNAME="${PREFIX}"
VNET_NAME="${PREFIX}-vnet"
AKSSUBNET_NAME="aks-subnet"
# DO NOT CHANGE FWSUBNET_NAME - This is currently a requirement for Azure Firewall.
FWSUBNET_NAME="AzureFirewallSubnet"
FWNAME="${PREFIX}-fw"
FWPUBLICIP_NAME="${PREFIX}-fwpublicip"
FWIPCONFIG_NAME="${PREFIX}-fwconfig"
FWROUTE_TABLE_NAME="${PREFIX}-fwrt"
FWROUTE_NAME="${PREFIX}-fwrn"
FWROUTE_NAME_INTERNET="${PREFIX}-fwinternet"
```
Any suggestions?
