### ISSUE TITLE
Intellisense showing invalid argument for az group name: --rg-name

### ISSUE THREAD

**Issue by aws-scripting-guy** [Microsoft/vscode-azurecli#44]
Using latest Azure CLI tools for VS Code 0.4.2

Steps to reproduce the issue:

1. Typing in .azcli file
az group create 
 Intellisense suggesting --rg-name as required argument for group name.  There is also missing help (stuck in Loading)

2. Right-click and Run line in the terminal
az group create --rg-name myGroup2 \\
 --location westeurope --tags 'Environment=Test'

3. Output
az group show: error: argument --name/-n/--resource-group/-g is required

![azure_cli_rg_name](https://user-images.githubusercontent.com/16693850/52021126-200f3b00-24f4-11e9-9657-abf9b68e2975.PNG)
![azure_cli_rg_name_missing_help](https://user-images.githubusercontent.com/16693850/52020229-d2dd9a00-24f0-11e9-8405-4606bda55ae3.PNG)

Solution:
pass argument -n or --name for resource group name

**Comment by chrmarti** [comment]
Can reproduce with Azure CLI 2.0.56.

**Comment by chrmarti** [comment]
This issue was moved to Azure/azure-cli#8395

**Comment by fxlv** [comment]
Same problem with "--vm-name" that is suggested by VSCode vs "--name" that is actually expected by az cli.
I think this should not be closed as it is very much an issue.

**Comment by vbdcb** [comment]
Same thing with "**az network vnet create**" 
--vnet-name should be --name 
--vnet-prefixes should be --address-prefix
