### ISSUE TITLE
PowerShell in cloud shell

### ISSUE THREAD

**Issue by akvaswani** [Microsoft/vscode-azurecli#45]
Issue Type: <b>Bug</b>

After logging in to Azure, the cursor always points to the 1,1 cursor location (top-left) of terminal instead of PS Azure:>. Even if you manage to type a command, it gets executed on a random keystroke.

Extension version: 0.4.2
VS Code version: Code 1.31.1 (1b8e8302e405050205e69b59abb3559592bb9e60, 2019-02-12T02:20:54.427Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (13.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

![image](https://user-images.githubusercontent.com/36173895/53056745-a5d63480-3469-11e9-954d-f0008e145011.png)

**Comment by chrmarti** [comment]
@akvaswani Could you update to the latest version of the extension (0.8.0) and confirm the problem is still there?

**Comment by akvaswani** [comment]
Yes, I am on 0.8.0 version.

**Comment by chrmarti** [comment]
@akvaswani Could you check if https://shell.azure.com has the same behavior?
