### ISSUE TITLE
Extension complaining az not on PATH

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-azurecli#46]
It's definitely there.

![image](https://user-images.githubusercontent.com/2193314/53502248-87bc9580-3a62-11e9-9310-ec07756ea80a.png)

System path:

![image](https://user-images.githubusercontent.com/2193314/53502332-b470ad00-3a62-11e9-96ea-20e99eda4cad.png)

VS Code Window path:

![image](https://user-images.githubusercontent.com/2193314/53502377-c81c1380-3a62-11e9-8eca-855e55123712.png)

az version:

```
azure-cli                         2.0.58 *
```

**Comment by Tyriar** [comment]
This was originally reported https://github.com/Microsoft/vscode-azurecli/issues/12

This happens after reloading the window, the extension host should have the right path as the renderer has it.

**Comment by chrmarti** [comment]
@Tyriar Is this still a problem? If the renderer has already picked up the PATH, the extension host should get it too. Is there anything that can go wrong there?

**Comment by Tyriar** [comment]
@chrmarti well it definitely happens on Windows when az is installed, maybe there's an error somewhere in https://github.com/Microsoft/vscode-azurecli/blob/6f259b8e38ebcde828909181cdc838d3d5aa5bf1/src/azService.ts#L118-L141 ?

**Comment by chrmarti** [comment]
@Tyriar That looks fine from what I see. Does `cmd.exe` find `az` too? (That's what Node.js uses.)

**Comment by chrmarti** [comment]
@Tyriar found and fixed it. Please update to the latest version. Thanks.

**Comment by Tyriar** [comment]
Nice 😃

**Comment by thakkarparth007** [comment]
Just adding a comment - this might also happen if you've installed az on the windows system, but your VS Code window is running from WSL where az might not have been installed. Happened with me, might help some random user.

**Comment by sgsvetko** [comment]
Hi guys,
Unfortunately, I'm facing the same problem in version Version - 0.6.0, as per the fix list in the extension same issue was solved in version 0.4.3
Any idea why it happens?

**Comment by gavinmcmenemy** [comment]
I'm also seeing this issue. It's really irritating.

**Comment by rahuljhaver** [comment]
Seeing the same issue
