### ISSUE TITLE
[Feature Request] Expose run commands for unsaved files

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/vscode-azurecli#6]
I created a new file (via `CMD+N`), and then changed its language mode to `Azure CLI Scrapbook` (via the command palette), but I noticed that the "run" commands (context menus or shortcut keys) weren't available. Once I saved the file (which I actually didn't want to do), then the context menus became available.

It would be cool if these commands were available for any file tagged as `Azure CLI Scrapbook`, since auto-completion, status bar updates, etc. already support it.

**Comment by chrmarti** [comment]
Seems to be a VSCode issue, opened: Microsoft/vscode#26873
