### ISSUE TITLE
Python process high cpu usage

### ISSUE THREAD

**Issue by fle108** [microsoft/vscode-azurecli#63]
VSCode Version: 1.40.2
OS Version: Windows10 v1909 Build 18363.476
Steps to Reproduce:

install or have installed azurecli on windows (typically : C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2
install or have installed azureclitools in vscode
create or edit file named *.azcli
Result: subprocess Visualstudiocode\python(32bit) located at C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe take 25-50% cpu all time even if file *.azcli is closed
when vscode restarted and no *.azcli is opened cpu is allright

Does this issue occur when all extensions are disabled?: No
if i disable extension "azure Cli tools" cpu is ok and when i re-enable it, python(32bit) is back at 40%cpu : \

**Comment by papymaj5** [comment]
Happening to me too with VSCode 1.42.0

**Comment by fle108** [comment]
i actually use a vm ubuntu 18.04 on local hyper-v for dev environment with vscode server installed. Every extensions are installed on it , the only installed locally is remote-ssh.
It works a lot better and solves me a problem with git file mode and NTFS as i'am now on true ext4 file system through this vm.

For sure it's not a fix but this config helped me a lot.

**Comment by fle108** [comment]
i use now pythonn from wsl2, no problem with.
