### ISSUE TITLE
How to run the selected text ? and what is the keyboard short cut to do the same?

### ISSUE THREAD

**Issue by megnath777** [microsoft/vscode-azurecli#69]
How to run the selected text (Command)? and what is the keyboard short cut to do the same?
I know it a stupid question but it is not obvious , I am new to VS code!

**Comment by chrmarti** [comment]
Press `F1` and search for that command:
![image](https://user-images.githubusercontent.com/9205389/78556862-0b24ea80-7810-11ea-9557-dc724fc30af6.png)

This is a built-in command from VS Code, I don't think there is a shortcut assigned, but you can certainly assign one (I use `Cmd + '` on Mac).

**Comment by chrmarti** [comment]
There is also documentation on assigning keybindings, HTH: https://code.visualstudio.com/docs/getstarted/keybindings
