### ISSUE TITLE
No intellisense/autocomplete for azcli

### ISSUE THREAD

**Issue by david-lilly** [microsoft/vscode-azurecli#71]
No intellisense/autocomplete for azcli in Visual Studio Code.

Operating System: Ubuntu 20.04 LTS
Kernel: Linux 5.4.0-29-generic

Visual Studio Code:

Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:10:24.511Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-29-generic snap

Azure CLI Tools Extension:
ms-vscode.azurecli 0.5.0

Azure CLI:

azure-cli (2.0.25)
acr (2.0.19)
acs (2.0.24)
advisor (0.1.1)
appservice (0.1.24)
backup (1.0.6)
batch (3.1.8)
batchai (0.1.4)
billing (0.1.7)
cdn (0.0.11)
cloud (2.0.11)
cognitiveservices (0.1.10)
command-modules-nspkg (2.0.1)
configure (2.0.13)
consumption (0.2.1)
container (0.1.16)
core (2.0.25)
cosmosdb (0.1.16)
dla (0.0.17)
dls (0.0.19)
eventgrid (0.1.8)
extension (0.0.7)
feedback (2.0.8)
find (0.2.8)
interactive (0.3.13)
iot (0.1.16)
keyvault (2.0.16)
lab (0.0.15)
monitor (0.1.0)
network (2.0.21)
nspkg (3.0.1)
profile (2.0.17)
rdbms (0.0.11)
redis (0.2.11)
reservations (0.1.1)
resource (2.0.21)
role (2.0.17)
servicefabric (0.0.9)
sql (2.0.19)
storage (2.0.23)
testsdk (0.1.0)
vm (2.0.24)

Python location '/snap/azure-cli/7/usr/bin/python3'
Extensions directory '/home/user/snap/azure-cli/7/.azure/cliextensions'

Python (Linux) 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

**Comment by mykelalvis** [comment]
Same for Fedora 32
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.19-300.fc32.x86_64
```

**Comment by mafranko** [comment]
It does not work as expected in Visual Studio Code either.

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Azure CLI Tools version 0.5.0.

**Comment by anvarich** [comment]
reinstalling helped me

**Comment by chrmarti** [comment]
Please make sure you are on the latest version of the CLI. (I have 2.9.1.)
