### ISSUE TITLE
The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by real1st** [microsoft/vscode-azurecli#78]
![image](https://user-images.githubusercontent.com/48164048/99840413-2f51f380-2b75-11eb-8feb-90e6be1f767b.png)
![image](https://user-images.githubusercontent.com/48164048/99840545-67f1cd00-2b75-11eb-9e49-450a34784c3f.png)
![image](https://user-images.githubusercontent.com/48164048/99840607-88218c00-2b75-11eb-92f2-3e2e8602a8a4.png)

Azure cli is successfully installed and working on Lens or powershell, but isn't working in vscode
uninstall/reinstall both tools doesn't help

please advice

**Comment by chrmarti** [comment]
Does it work when you start VS Code from the command line (where it `az` works)?

**Comment by real1st** [comment]
fixed

thank you!

it was extensions issue's 

don't know which one

solution: delete all extensions from directory where application is installed
