### ISSUE TITLE
IntelliSense feature fail in the Azure CLI's vscode extension

### ISSUE THREAD

**Issue by wu5bocheng** [microsoft/vscode-azurecli#88]
**Issue Summary**: The IntelliSense feature in the Azure CLI's vscode extension is not working on my Windows 11 machine. Code hints and completions do not appear. I suspect that the issue may be related to a conflict with the copilot extension, which is also installed, but disabling copilot did not resolve the issue.

**Steps to Reproduce**:

1. Open vscode on a Windows 11 machine
2. Install Azure CLI extension
3. Install copilot extension
4. Attempt to use IntelliSense feature in Azure CLI extension
5. Observe that code hints and completions do not appear

**Expected Result**: IntelliSense feature in Azure CLI extension should provide code hints and completions

**Actual Result**: Code hints and completions do not appear when using the IntelliSense feature in Azure CLI extension

**Notes**

- Copilot extension has been disabled but it did not resolve the issue

**Request for Help** I am requesting help to resolve this issue with the IntelliSense feature in the Azure CLI's vscode extension. Any suggestions or solutions would be greatly appreciated.
<img width="432" alt="image" src="https://user-images.githubusercontent.com/79819545/213616971-0c979716-5584-4d15-bd97-cf3c017da8f9.png">

**Comment by bluebrown** [comment]
It works ocasionally but its super flow.
