### ISSUE TITLE
OSX: Run Current Command Not Available

### ISSUE THREAD

**Issue by jstabl** [Microsoft/vscode-azurecli#9]
I am not seeing Run Current Command option when using OSX also keyboard shortcuts do not work either. It's possible I am missing something?

 VS Code 1.12.2 and vscode-azurecli version 0.1.0.

**Comment by chrmarti** [comment]
Is this with a saved `.azcli` file? Does it show any coloring?

**Comment by jstabl** [comment]
Ah, I just created a blank file and changed the language to Azure CLI Scrapbook. As soon as I created a file with .azcli the extension started to work. Thank you.

**Comment by chrmarti** [comment]
This is fixed in master (#6)
